"""removed user.nextincomedate column

Revision ID: ea8143817887
Revises: 6fc12ca78cad
Create Date: 2025-08-31 23:35:31.908026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea8143817887'
down_revision = '6fc12ca78cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('NextIncomeDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NextIncomeDate', sa.DATE(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
