name: Docker Image CI

on:
  push:
    branches: [ "main", "kuber-test" ]
  pull_request:
    branches: [ "main", "kuber-test" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t dcabriales/spender-flask:${{ github.ref_name }} .
